url: http://rensa.co
baseurl:
twitter_username: rensa_co
github_username: rensa

# Site settings
title: "rensa.co"
email: me@rensa.co
description: "I'm James, a climate change researcher doing a PhD with UNSW Australia."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fe9036
  secondary: fe7403  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: James Goldie
  pic: 1
  position: PhD Candidate
  social:
    - title: twitter
      url: http://twitter.com/rensa_co
    - title: linkedin
      url: http://linkedin.com/in/rensaco
    - title: stack-exchange
      url: http://stackexchange.com/users/3610237/rensa
    - title: medium
      url: http://medium.com/@rensa
    - title: youtube
      url: http://youtube.com/user/rensadotco

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rensa_co
  - title: linkedin
    url: http://linkedin.com/in/rensaco
  - title: stack-exchange
    url: http://stackexchange.com/users/3610237/rensa
  - title: medium
    url: http://medium.com/@rensa
  - title: youtube
    url: http://youtube.com/c/RensaCo
  - title:google-plus
    url: https://plus.google.com/+RensaCo

# Postal address (add as many lines as necessary)
address:
  - line: "J7.222, Jaeger Bldg J7"
  - line: The Australian National University
  - line: "Mills Rd, Acton, ACT 2601"

# Build settings
markdown: kramdown
permalink: pretty