url: http://rensa.co
baseurl:
twitter_username: rensa_co
github_username: rensa

# Site settings
title: "rensa.co"
email: me@rensa.co
description: "I'm James, a climate change researcher doing a PhD with UNSW Australia."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fe9036
  secondary: fe7403  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: James Goldie
  pic: 1
  position: PhD Candidate
  social:
    - title: facebook
      url: http://facebook.com/rensa.co
    - title: twitter
      url: http://twitter.com/rensa_co
    - title: linkedin
      url: http://linkedin.com/in/rensaco
    - title: stack-exchange
      url: http://stackexchange.com/users/3610237/rensa
    - title: github
      url: https://github.com/rensa
    - title: youtube
      url: http://youtube.com/c/RensaCo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/rensa.co
  - title: twitter
    url: http://twitter.com/rensa_co
  - title: linkedin
    url: http://linkedin.com/in/rensaco
  - title: stack-exchange
    url: http://stackexchange.com/users/3610237/rensa
  - title: github
    url: https://github.com/rensa
  - title: youtube
    url: http://youtube.com/c/RensaCo

# Build settings
markdown: redcarpet
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/:categories/:num"

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
