# Site settings
title: "James Goldie"
email: "me@rensa.co"
url: http://rensa.co
description: "PhD student (climate + health) @ UNSW + ANU. Climate, public health, gaming, code, vfx, data, science!"
twitter_username: rensa_co

# paginate: 5
# paginate_path: "/blog/page-:num"
google_analytics: googlee53d5dca6b1758f3
default_img: /assets/me.jpg

# Profile settings
name: James Goldie
profile_img: /assets/me.jpg
profile: "PhD student (climate + health). I build stuff to help people understand discoveries and change their feelings on issues." 
social:
  facebook: https://facebook.com/rensa
  twitter: https://twitter.com/rensa_co
  linkedin: http://au.linkedin.com/in/rensaco
  github: http://github.com/rensa
  stack-overflow: http://stackoverflow.com/story/rensa
  flask: https://www.researchgate.net/profile/James_Goldie2


# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: "/:categories/:title/"

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
