# Site settings
title: "Please Hold"
subtitle: "rensa.co"
email: "me@rensa.co"
url: https://rensa.co
baseurl: /please-hold
description: "Track the time you waste with Centrelink. Everything stays on your device."
twitter_username: rensa_co

# paginate: 5
# paginate_path: "/blog/page-:num"
google_analytics: UA-104057153-2
default_img: /assets/me.jpg

# Profile settings
name: James Goldie
profile_img: /assets/me.jpg
profile: "PhD student (climate change + health). I also code and build things for fun and for social change." 
social:
  facebook: https://facebook.com/rensa
  twitter: https://twitter.com/rensa_co
  linkedin: https://au.linkedin.com/in/rensaco
  github: https://github.com/rensa
  stack-overflow: https://stackoverflow.com/story/rensa
  flask: https://www.researchgate.net/profile/James_Goldie2
  envelope-o: mailto:me@rensa.co
  key: https://keybase.io/rensa

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: "/:categories/:title/"

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

# other notes for index.html:
# - use my_css and my_js to include a custom style sheet or js
# - use ext_js (bulleted) to include external js libs (full path!)
# - use image to point to a mast image in /assets
# - put the page html in _includes/project-content.html